name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Deploy to Digital Ocean
        run: |
          ssh -o StrictHostKeyChecking=no  ${{ secrets.DO_CONECTION_URI }} "
            if [ ! -d ~/WonderPeak_backend ]; then
              git clone https://github.com/gregoriocarranza/WonderPeak_backend.git ~/WonderPeak_backend
            else
              cd ~/WonderPeak_backend && git pull
            fi
            cd ~/WonderPeak_backend
            docker-compose up --build -d
          "
